GET http://localhost:8080/posts/15
Accept: application/json;version=1

###

GET http://localhost:8080/posts/15
Accept: application/json;version=2

###

GET http://localhost:8080/posts/15
Accept: application/json;version=3

###

GET http://localhost:8080/posts/15

###